# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Database.PostgreSql.Model.SecurityAlertPolicyProperties do
  @moduledoc """
  Properties of a security alert policy.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"state",
    :"disabledAlerts",
    :"emailAddresses",
    :"emailAccountAdmins",
    :"storageEndpoint",
    :"storageAccountAccessKey",
    :"retentionDays"
  ]

  @type t :: %__MODULE__{
    :"state" => String.t,
    :"disabledAlerts" => [String.t],
    :"emailAddresses" => [String.t],
    :"emailAccountAdmins" => boolean(),
    :"storageEndpoint" => String.t,
    :"storageAccountAccessKey" => String.t,
    :"retentionDays" => integer()
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Database.PostgreSql.Model.SecurityAlertPolicyProperties do
  def decode(value, _options) do
    value
  end
end

