# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Database.PostgreSql.Model.ServerUpdateParameters do
  @moduledoc """
  Parameters allowd to update for a server.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"sku",
    :"properties",
    :"tags"
  ]

  @type t :: %__MODULE__{
    :"sku" => Sku,
    :"properties" => ServerUpdateParametersProperties,
    :"tags" => %{optional(String.t) => String.t}
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Database.PostgreSql.Model.ServerUpdateParameters do
  import Microsoft.Azure.Management.Database.PostgreSql.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"sku", :struct, Microsoft.Azure.Management.Database.PostgreSql.Model.Sku, options)
    |> deserialize(:"properties", :struct, Microsoft.Azure.Management.Database.PostgreSql.Model.ServerUpdateParametersProperties, options)
  end
end

