# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Resources.Model.ResourceGroupFilter do
  @moduledoc """
  Resource group filter.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"tagName",
    :"tagValue"
  ]

  @type t :: %__MODULE__{
    :"tagName" => String.t,
    :"tagValue" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Resources.Model.ResourceGroupFilter do
  def decode(value, _options) do
    value
  end
end

