# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Resources.Model.TemplateLink do
  @moduledoc """
  Entity representing the reference to the template.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"uri",
    :"contentVersion"
  ]

  @type t :: %__MODULE__{
    :"uri" => String.t,
    :"contentVersion" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Resources.Model.TemplateLink do
  def decode(value, _options) do
    value
  end
end

