# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Preview.Containers.Model.BuildTaskUpdateParameters do
  @moduledoc """
  The parameters for updating a build task.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"properties",
    :"tags"
  ]

  @type t :: %__MODULE__{
    :"properties" => BuildTaskPropertiesUpdateParameters,
    :"tags" => %{optional(String.t) => String.t}
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Preview.Containers.Model.BuildTaskUpdateParameters do
  import Microsoft.Azure.Management.Preview.Containers.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"properties", :struct, Microsoft.Azure.Management.Preview.Containers.Model.BuildTaskPropertiesUpdateParameters, options)
  end
end

