# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Preview.Containers.Model.BuildProperties do
  @moduledoc """
  The properties for a build.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"buildId",
    :"status",
    :"lastUpdatedTime",
    :"buildType",
    :"createTime",
    :"startTime",
    :"finishTime",
    :"outputImages",
    :"buildTask",
    :"imageUpdateTrigger",
    :"gitCommitTrigger",
    :"isArchiveEnabled",
    :"platform",
    :"provisioningState"
  ]

  @type t :: %__MODULE__{
    :"buildId" => String.t,
    :"status" => String.t,
    :"lastUpdatedTime" => DateTime.t,
    :"buildType" => String.t,
    :"createTime" => DateTime.t,
    :"startTime" => DateTime.t,
    :"finishTime" => DateTime.t,
    :"outputImages" => [ImageDescriptor],
    :"buildTask" => String.t,
    :"imageUpdateTrigger" => ImageUpdateTrigger,
    :"gitCommitTrigger" => GitCommitTrigger,
    :"isArchiveEnabled" => boolean(),
    :"platform" => PlatformProperties,
    :"provisioningState" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Preview.Containers.Model.BuildProperties do
  import Microsoft.Azure.Management.Preview.Containers.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"outputImages", :list, Microsoft.Azure.Management.Preview.Containers.Model.ImageDescriptor, options)
    |> deserialize(:"imageUpdateTrigger", :struct, Microsoft.Azure.Management.Preview.Containers.Model.ImageUpdateTrigger, options)
    |> deserialize(:"gitCommitTrigger", :struct, Microsoft.Azure.Management.Preview.Containers.Model.GitCommitTrigger, options)
    |> deserialize(:"platform", :struct, Microsoft.Azure.Management.Preview.Containers.Model.PlatformProperties, options)
  end
end

