# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Preview.Containers.Model.ImageDescriptor do
  @moduledoc """
  Properties for a registry image.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"registry",
    :"repository",
    :"tag",
    :"digest"
  ]

  @type t :: %__MODULE__{
    :"registry" => String.t,
    :"repository" => String.t,
    :"tag" => String.t,
    :"digest" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Preview.Containers.Model.ImageDescriptor do
  def decode(value, _options) do
    value
  end
end

