# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.ApplicationGatewayRequestRoutingRulePropertiesFormat do
  @moduledoc """
  Properties of request routing rule of the application gateway.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ruleType",
    :"backendAddressPool",
    :"backendHttpSettings",
    :"httpListener",
    :"urlPathMap",
    :"redirectConfiguration",
    :"provisioningState"
  ]

  @type t :: %__MODULE__{
    :"ruleType" => String.t,
    :"backendAddressPool" => SubResource,
    :"backendHttpSettings" => SubResource,
    :"httpListener" => SubResource,
    :"urlPathMap" => SubResource,
    :"redirectConfiguration" => SubResource,
    :"provisioningState" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.ApplicationGatewayRequestRoutingRulePropertiesFormat do
  import Microsoft.Azure.Management.Network.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"backendAddressPool", :struct, Microsoft.Azure.Management.Network.Model.SubResource, options)
    |> deserialize(:"backendHttpSettings", :struct, Microsoft.Azure.Management.Network.Model.SubResource, options)
    |> deserialize(:"httpListener", :struct, Microsoft.Azure.Management.Network.Model.SubResource, options)
    |> deserialize(:"urlPathMap", :struct, Microsoft.Azure.Management.Network.Model.SubResource, options)
    |> deserialize(:"redirectConfiguration", :struct, Microsoft.Azure.Management.Network.Model.SubResource, options)
  end
end

