# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.ApplicationGatewayPathRulePropertiesFormat do
  @moduledoc """
  Properties of path rule of an application gateway.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"paths",
    :"backendAddressPool",
    :"backendHttpSettings",
    :"redirectConfiguration",
    :"provisioningState"
  ]

  @type t :: %__MODULE__{
    :"paths" => [String.t],
    :"backendAddressPool" => SubResource,
    :"backendHttpSettings" => SubResource,
    :"redirectConfiguration" => SubResource,
    :"provisioningState" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.ApplicationGatewayPathRulePropertiesFormat do
  import Microsoft.Azure.Management.Network.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"backendAddressPool", :struct, Microsoft.Azure.Management.Network.Model.SubResource, options)
    |> deserialize(:"backendHttpSettings", :struct, Microsoft.Azure.Management.Network.Model.SubResource, options)
    |> deserialize(:"redirectConfiguration", :struct, Microsoft.Azure.Management.Network.Model.SubResource, options)
  end
end

