# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.CloudErrorBody do
  @moduledoc """
  The content of an error returned by the Azure Resource Manager
  """

  @derive [Poison.Encoder]
  defstruct [
    :"code",
    :"message",
    :"target",
    :"details"
  ]

  @type t :: %__MODULE__{
    :"code" => String.t,
    :"message" => String.t,
    :"target" => String.t,
    :"details" => [CloudErrorBody]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.CloudErrorBody do
  import Microsoft.Azure.Management.Network.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"details", :list, Microsoft.Azure.Management.Network.Model.CloudErrorBody, options)
  end
end

