# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.ConnectivityDestination do
  @moduledoc """
  Parameters that define destination of connection.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"resourceId",
    :"address",
    :"port"
  ]

  @type t :: %__MODULE__{
    :"resourceId" => String.t,
    :"address" => String.t,
    :"port" => integer()
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.ConnectivityDestination do
  def decode(value, _options) do
    value
  end
end

