# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.ExpressRouteCircuitRoutesTable do
  @moduledoc """
  The routes table associated with the ExpressRouteCircuit
  """

  @derive [Poison.Encoder]
  defstruct [
    :"network",
    :"nextHop",
    :"locPrf",
    :"weight",
    :"path"
  ]

  @type t :: %__MODULE__{
    :"network" => String.t,
    :"nextHop" => String.t,
    :"locPrf" => String.t,
    :"weight" => integer(),
    :"path" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.ExpressRouteCircuitRoutesTable do
  def decode(value, _options) do
    value
  end
end

