# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.HeatMapEndpoint do
  @moduledoc """
  Class which is a sparse representation of a Traffic Manager endpoint.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"resourceId",
    :"endpointId"
  ]

  @type t :: %__MODULE__{
    :"resourceId" => String.t,
    :"endpointId" => integer()
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.HeatMapEndpoint do
  def decode(value, _options) do
    value
  end
end

