# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.Ipv6ExpressRouteCircuitPeeringConfig do
  @moduledoc """
  Contains IPv6 peering config.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"primaryPeerAddressPrefix",
    :"secondaryPeerAddressPrefix",
    :"microsoftPeeringConfig",
    :"routeFilter",
    :"state"
  ]

  @type t :: %__MODULE__{
    :"primaryPeerAddressPrefix" => String.t,
    :"secondaryPeerAddressPrefix" => String.t,
    :"microsoftPeeringConfig" => ExpressRouteCircuitPeeringConfig,
    :"routeFilter" => RouteFilter,
    :"state" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.Ipv6ExpressRouteCircuitPeeringConfig do
  import Microsoft.Azure.Management.Network.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"microsoftPeeringConfig", :struct, Microsoft.Azure.Management.Network.Model.ExpressRouteCircuitPeeringConfig, options)
    |> deserialize(:"routeFilter", :struct, Microsoft.Azure.Management.Network.Model.RouteFilter, options)
  end
end

