# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.PublicIpAddressDnsSettings do
  @moduledoc """
  Contains FQDN of the DNS record associated with the public IP address
  """

  @derive [Poison.Encoder]
  defstruct [
    :"domainNameLabel",
    :"fqdn",
    :"reverseFqdn"
  ]

  @type t :: %__MODULE__{
    :"domainNameLabel" => String.t,
    :"fqdn" => String.t,
    :"reverseFqdn" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.PublicIpAddressDnsSettings do
  def decode(value, _options) do
    value
  end
end

