# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.ResourceNavigationLinkFormat do
  @moduledoc """
  Properties of ResourceNavigationLink.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"linkedResourceType",
    :"link",
    :"provisioningState"
  ]

  @type t :: %__MODULE__{
    :"linkedResourceType" => String.t,
    :"link" => String.t,
    :"provisioningState" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.ResourceNavigationLinkFormat do
  def decode(value, _options) do
    value
  end
end

