# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.SoaRecord do
  @moduledoc """
  An SOA record.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"host",
    :"email",
    :"serialNumber",
    :"refreshTime",
    :"retryTime",
    :"expireTime",
    :"minimumTTL"
  ]

  @type t :: %__MODULE__{
    :"host" => String.t,
    :"email" => String.t,
    :"serialNumber" => integer(),
    :"refreshTime" => integer(),
    :"retryTime" => integer(),
    :"expireTime" => integer(),
    :"minimumTTL" => integer()
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.SoaRecord do
  def decode(value, _options) do
    value
  end
end

