# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.TransportProtocol do
  @moduledoc """
  The transport protocol for the endpoint. Possible values are &#39;Udp&#39; or &#39;Tcp&#39; or &#39;All&#39;.
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.TransportProtocol do
  def decode(value, _options) do
    value
  end
end

