# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.VpnClientConfiguration do
  @moduledoc """
  VpnClientConfiguration for P2S client.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"vpnClientAddressPool",
    :"vpnClientRootCertificates",
    :"vpnClientRevokedCertificates",
    :"vpnClientProtocols",
    :"vpnClientIpsecPolicies",
    :"radiusServerAddress",
    :"radiusServerSecret"
  ]

  @type t :: %__MODULE__{
    :"vpnClientAddressPool" => AddressSpace,
    :"vpnClientRootCertificates" => [VpnClientRootCertificate],
    :"vpnClientRevokedCertificates" => [VpnClientRevokedCertificate],
    :"vpnClientProtocols" => [String.t],
    :"vpnClientIpsecPolicies" => [IpsecPolicy],
    :"radiusServerAddress" => String.t,
    :"radiusServerSecret" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.VpnClientConfiguration do
  import Microsoft.Azure.Management.Network.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"vpnClientAddressPool", :struct, Microsoft.Azure.Management.Network.Model.AddressSpace, options)
    |> deserialize(:"vpnClientRootCertificates", :list, Microsoft.Azure.Management.Network.Model.VpnClientRootCertificate, options)
    |> deserialize(:"vpnClientRevokedCertificates", :list, Microsoft.Azure.Management.Network.Model.VpnClientRevokedCertificate, options)
    |> deserialize(:"vpnClientIpsecPolicies", :list, Microsoft.Azure.Management.Network.Model.IpsecPolicy, options)
  end
end

