# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Advisor.Model.RecommendationProperties do
  @moduledoc """
  The properties of the recommendation.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"category",
    :"impact",
    :"impactedField",
    :"impactedValue",
    :"lastUpdated",
    :"metadata",
    :"recommendationTypeId",
    :"risk",
    :"shortDescription",
    :"suppressionIds"
  ]

  @type t :: %__MODULE__{
    :"category" => String.t,
    :"impact" => String.t,
    :"impactedField" => String.t,
    :"impactedValue" => String.t,
    :"lastUpdated" => DateTime.t,
    :"metadata" => %{optional(String.t) => Object},
    :"recommendationTypeId" => String.t,
    :"risk" => String.t,
    :"shortDescription" => ShortDescription,
    :"suppressionIds" => [String.t]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Advisor.Model.RecommendationProperties do
  import Microsoft.Azure.Management.Advisor.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"metadata", :map, Microsoft.Azure.Management.Advisor.Model.Object, options)
    |> deserialize(:"shortDescription", :struct, Microsoft.Azure.Management.Advisor.Model.ShortDescription, options)
  end
end

