# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Database.PostgreSql.Api.ServerSecurityAlertPolicies do
  @moduledoc """
  API calls for all endpoints tagged `ServerSecurityAlertPolicies`.
  """

  alias Microsoft.Azure.Management.Database.PostgreSql.Connection
  import Microsoft.Azure.Management.Database.PostgreSql.RequestBuilder


  @doc """
  Creates or updates a threat detection policy.

  ## Parameters

  - connection (Microsoft.Azure.Management.Database.PostgreSql.Connection): Connection to server
  - resource_group_name (String.t): The name of the resource group that contains the resource. You can obtain this value from the Azure Resource Manager API or the portal.
  - server_name (String.t): The name of the server.
  - security_alert_policy_name (String.t): The name of the threat detection policy.
  - parameters (ServerSecurityAlertPolicy): The server security alert policy.
  - subscription_id (String.t): The subscription ID that identifies an Azure subscription.
  - api_version (String.t): The API version to use for the request.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Database.PostgreSql.Model.ServerSecurityAlertPolicy{}} on success
  {:error, info} on failure
  """
  @spec server_security_alert_policies_create_or_update(Tesla.Env.client, String.t, String.t, String.t, Microsoft.Azure.Management.Database.PostgreSql.Model.ServerSecurityAlertPolicy.t, String.t, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Database.PostgreSql.Model.ServerSecurityAlertPolicy.t} | {:error, Tesla.Env.t}
  def server_security_alert_policies_create_or_update(connection, resource_group_name, server_name, security_alert_policy_name, parameters, subscription_id, api_version, _opts \\ []) do
    %{}
    |> method(:put)
    |> url("/subscriptions/#{subscription_id}/resourceGroups/#{resource_group_name}/providers/Microsoft.DBforPostgreSQL/servers/#{server_name}/securityAlertPolicies/#{security_alert_policy_name}")
    |> add_param(:body, :body, parameters)
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Database.PostgreSql.Model.ServerSecurityAlertPolicy{})
  end

  @doc """
  Get a server&#39;s security alert policy.

  ## Parameters

  - connection (Microsoft.Azure.Management.Database.PostgreSql.Connection): Connection to server
  - resource_group_name (String.t): The name of the resource group that contains the resource. You can obtain this value from the Azure Resource Manager API or the portal.
  - server_name (String.t): The name of the server.
  - security_alert_policy_name (String.t): The name of the security alert policy.
  - subscription_id (String.t): The subscription ID that identifies an Azure subscription.
  - api_version (String.t): The API version to use for the request.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Database.PostgreSql.Model.ServerSecurityAlertPolicy{}} on success
  {:error, info} on failure
  """
  @spec server_security_alert_policies_get(Tesla.Env.client, String.t, String.t, String.t, String.t, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Database.PostgreSql.Model.ServerSecurityAlertPolicy.t} | {:error, Tesla.Env.t}
  def server_security_alert_policies_get(connection, resource_group_name, server_name, security_alert_policy_name, subscription_id, api_version, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/subscriptions/#{subscription_id}/resourceGroups/#{resource_group_name}/providers/Microsoft.DBforPostgreSQL/servers/#{server_name}/securityAlertPolicies/#{security_alert_policy_name}")
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Database.PostgreSql.Model.ServerSecurityAlertPolicy{})
  end
end
