# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Database.PostgreSql.Api.VirtualNetworkRules do
  @moduledoc """
  API calls for all endpoints tagged `VirtualNetworkRules`.
  """

  alias Microsoft.Azure.Management.Database.PostgreSql.Connection
  import Microsoft.Azure.Management.Database.PostgreSql.RequestBuilder


  @doc """
  Creates or updates an existing virtual network rule.

  ## Parameters

  - connection (Microsoft.Azure.Management.Database.PostgreSql.Connection): Connection to server
  - resource_group_name (String.t): The name of the resource group that contains the resource. You can obtain this value from the Azure Resource Manager API or the portal.
  - server_name (String.t): The name of the server.
  - subscription_id (String.t): The subscription ID that identifies an Azure subscription.
  - api_version (String.t): The API version to use for the request.
  - virtual_network_rule_name (String.t): The name of the virtual network rule.
  - parameters (VirtualNetworkRule): The requested virtual Network Rule Resource state.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Database.PostgreSql.Model.VirtualNetworkRule{}} on success
  {:error, info} on failure
  """
  @spec virtual_network_rules_create_or_update(Tesla.Env.client, String.t, String.t, String.t, String.t, String.t, Microsoft.Azure.Management.Database.PostgreSql.Model.VirtualNetworkRule.t, keyword()) :: {:ok, Microsoft.Azure.Management.Database.PostgreSql.Model.VirtualNetworkRule.t} | {:error, Tesla.Env.t}
  def virtual_network_rules_create_or_update(connection, resource_group_name, server_name, subscription_id, api_version, virtual_network_rule_name, parameters, _opts \\ []) do
    %{}
    |> method(:put)
    |> url("/subscriptions/#{subscription_id}/resourceGroups/#{resource_group_name}/providers/Microsoft.DBforPostgreSQL/servers/#{server_name}/virtualNetworkRules/#{virtual_network_rule_name}")
    |> add_param(:query, :"api-version", api_version)
    |> add_param(:body, :body, parameters)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Database.PostgreSql.Model.VirtualNetworkRule{})
  end

  @doc """
  Deletes the virtual network rule with the given name.

  ## Parameters

  - connection (Microsoft.Azure.Management.Database.PostgreSql.Connection): Connection to server
  - resource_group_name (String.t): The name of the resource group that contains the resource. You can obtain this value from the Azure Resource Manager API or the portal.
  - server_name (String.t): The name of the server.
  - virtual_network_rule_name (String.t): The name of the virtual network rule.
  - subscription_id (String.t): The subscription ID that identifies an Azure subscription.
  - api_version (String.t): The API version to use for the request.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec virtual_network_rules_delete(Tesla.Env.client, String.t, String.t, String.t, String.t, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def virtual_network_rules_delete(connection, resource_group_name, server_name, virtual_network_rule_name, subscription_id, api_version, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/subscriptions/#{subscription_id}/resourceGroups/#{resource_group_name}/providers/Microsoft.DBforPostgreSQL/servers/#{server_name}/virtualNetworkRules/#{virtual_network_rule_name}")
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """
  Gets a virtual network rule.

  ## Parameters

  - connection (Microsoft.Azure.Management.Database.PostgreSql.Connection): Connection to server
  - resource_group_name (String.t): The name of the resource group that contains the resource. You can obtain this value from the Azure Resource Manager API or the portal.
  - server_name (String.t): The name of the server.
  - subscription_id (String.t): The subscription ID that identifies an Azure subscription.
  - api_version (String.t): The API version to use for the request.
  - virtual_network_rule_name (String.t): The name of the virtual network rule.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Database.PostgreSql.Model.VirtualNetworkRule{}} on success
  {:error, info} on failure
  """
  @spec virtual_network_rules_get(Tesla.Env.client, String.t, String.t, String.t, String.t, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Database.PostgreSql.Model.VirtualNetworkRule.t} | {:error, Tesla.Env.t}
  def virtual_network_rules_get(connection, resource_group_name, server_name, subscription_id, api_version, virtual_network_rule_name, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/subscriptions/#{subscription_id}/resourceGroups/#{resource_group_name}/providers/Microsoft.DBforPostgreSQL/servers/#{server_name}/virtualNetworkRules/#{virtual_network_rule_name}")
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Database.PostgreSql.Model.VirtualNetworkRule{})
  end

  @doc """
  Gets a list of virtual network rules in a server.

  ## Parameters

  - connection (Microsoft.Azure.Management.Database.PostgreSql.Connection): Connection to server
  - resource_group_name (String.t): The name of the resource group that contains the resource. You can obtain this value from the Azure Resource Manager API or the portal.
  - server_name (String.t): The name of the server.
  - subscription_id (String.t): The subscription ID that identifies an Azure subscription.
  - api_version (String.t): The API version to use for the request.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Database.PostgreSql.Model.VirtualNetworkRuleListResult{}} on success
  {:error, info} on failure
  """
  @spec virtual_network_rules_list_by_server(Tesla.Env.client, String.t, String.t, String.t, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Database.PostgreSql.Model.VirtualNetworkRuleListResult.t} | {:error, Tesla.Env.t}
  def virtual_network_rules_list_by_server(connection, resource_group_name, server_name, subscription_id, api_version, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/subscriptions/#{subscription_id}/resourceGroups/#{resource_group_name}/providers/Microsoft.DBforPostgreSQL/servers/#{server_name}/virtualNetworkRules")
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Database.PostgreSql.Model.VirtualNetworkRuleListResult{})
  end
end
