# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.DbForPostgresql.Model.Sku do
  @moduledoc """
  Billing information related properties of a server.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"tier",
    :"capacity",
    :"size",
    :"family"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"tier" => String.t,
    :"capacity" => integer(),
    :"size" => String.t,
    :"family" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.DbForPostgresql.Model.Sku do
  def decode(value, _options) do
    value
  end
end

