# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.EventGrid.Model.Operation do
  @moduledoc """
  Represents an operation returned by the GetOperations request
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"display",
    :"origin",
    :"properties"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"display" => OperationInfo,
    :"origin" => String.t,
    :"properties" => Object
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.EventGrid.Model.Operation do
  import Microsoft.Azure.Management.EventGrid.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"display", :struct, Microsoft.Azure.Management.EventGrid.Model.OperationInfo, options)
    #|> deserialize(:"properties", :struct, Microsoft.Azure.Management.EventGrid.Model.Object, options)
  end
end

