# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.EventGrid.Model.TopicSharedAccessKeys do
  @moduledoc """
  Shared access keys of the Topic
  """

  @derive [Poison.Encoder]
  defstruct [
    :"key1",
    :"key2"
  ]

  @type t :: %__MODULE__{
    :"key1" => String.t,
    :"key2" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.EventGrid.Model.TopicSharedAccessKeys do
  def decode(value, _options) do
    value
  end
end

