# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.EventGrid.Model.TopicTypeProperties do
  @moduledoc """
  Properties of a topic type.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"provider",
    :"displayName",
    :"description",
    :"resourceRegionType",
    :"provisioningState",
    :"supportedLocations"
  ]

  @type t :: %__MODULE__{
    :"provider" => String.t,
    :"displayName" => String.t,
    :"description" => String.t,
    :"resourceRegionType" => String.t,
    :"provisioningState" => String.t,
    :"supportedLocations" => [String.t]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.EventGrid.Model.TopicTypeProperties do
  def decode(value, _options) do
    value
  end
end

