# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Api.VirtualMachineExtensions do
  @moduledoc """
  API calls for all endpoints tagged `VirtualMachineExtensions`.
  """

  alias Microsoft.Azure.Management.Compute.Connection
  import Microsoft.Azure.Management.Compute.RequestBuilder


  @doc """
  The operation to create or update the extension.

  ## Parameters

  - connection (Microsoft.Azure.Management.Compute.Connection): Connection to server
  - resource_group_name (String.t): The name of the resource group.
  - vm_name (String.t): The name of the virtual machine where the extension should be created or updated.
  - vm_extension_name (String.t): The name of the virtual machine extension.
  - extension_parameters (VirtualMachineExtension): Parameters supplied to the Create Virtual Machine Extension operation.
  - api_version (String.t): Client Api Version.
  - subscription_id (String.t): Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Compute.Model.VirtualMachineExtension{}} on success
  {:error, info} on failure
  """
  @spec virtual_machine_extensions_create_or_update(Tesla.Env.client, String.t, String.t, String.t, Microsoft.Azure.Management.Compute.Model.VirtualMachineExtension.t, String.t, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Compute.Model.VirtualMachineExtension.t} | {:error, Tesla.Env.t}
  def virtual_machine_extensions_create_or_update(connection, resource_group_name, vm_name, vm_extension_name, extension_parameters, api_version, subscription_id, _opts \\ []) do
    %{}
    |> method(:put)
    |> url("/subscriptions/#{subscription_id}/resourceGroups/#{resource_group_name}/providers/Microsoft.Compute/virtualMachines/#{vm_name}/extensions/#{vm_extension_name}")
    |> add_param(:body, :body, extension_parameters)
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Compute.Model.VirtualMachineExtension{})
  end

  @doc """
  The operation to delete the extension.

  ## Parameters

  - connection (Microsoft.Azure.Management.Compute.Connection): Connection to server
  - resource_group_name (String.t): The name of the resource group.
  - vm_name (String.t): The name of the virtual machine where the extension should be deleted.
  - vm_extension_name (String.t): The name of the virtual machine extension.
  - api_version (String.t): Client Api Version.
  - subscription_id (String.t): Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Compute.Model.OperationStatusResponse{}} on success
  {:error, info} on failure
  """
  @spec virtual_machine_extensions_delete(Tesla.Env.client, String.t, String.t, String.t, String.t, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Compute.Model.OperationStatusResponse.t} | {:error, Tesla.Env.t}
  def virtual_machine_extensions_delete(connection, resource_group_name, vm_name, vm_extension_name, api_version, subscription_id, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/subscriptions/#{subscription_id}/resourceGroups/#{resource_group_name}/providers/Microsoft.Compute/virtualMachines/#{vm_name}/extensions/#{vm_extension_name}")
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Compute.Model.OperationStatusResponse{})
  end

  @doc """
  The operation to get the extension.

  ## Parameters

  - connection (Microsoft.Azure.Management.Compute.Connection): Connection to server
  - resource_group_name (String.t): The name of the resource group.
  - vm_name (String.t): The name of the virtual machine containing the extension.
  - vm_extension_name (String.t): The name of the virtual machine extension.
  - api_version (String.t): Client Api Version.
  - subscription_id (String.t): Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
  - opts (KeywordList): [optional] Optional parameters
    - :__expand (String.t): The expand expression to apply on the operation.

  ## Returns

  {:ok, %Microsoft.Azure.Management.Compute.Model.VirtualMachineExtension{}} on success
  {:error, info} on failure
  """
  @spec virtual_machine_extensions_get(Tesla.Env.client, String.t, String.t, String.t, String.t, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Compute.Model.VirtualMachineExtension.t} | {:error, Tesla.Env.t}
  def virtual_machine_extensions_get(connection, resource_group_name, vm_name, vm_extension_name, api_version, subscription_id, opts \\ []) do
    optional_params = %{
      :"$expand" => :query
    }
    %{}
    |> method(:get)
    |> url("/subscriptions/#{subscription_id}/resourceGroups/#{resource_group_name}/providers/Microsoft.Compute/virtualMachines/#{vm_name}/extensions/#{vm_extension_name}")
    |> add_param(:query, :"api-version", api_version)
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Compute.Model.VirtualMachineExtension{})
  end

  @doc """
  The operation to update the extension.

  ## Parameters

  - connection (Microsoft.Azure.Management.Compute.Connection): Connection to server
  - resource_group_name (String.t): The name of the resource group.
  - vm_name (String.t): The name of the virtual machine where the extension should be updated.
  - vm_extension_name (String.t): The name of the virtual machine extension.
  - extension_parameters (VirtualMachineExtensionUpdate): Parameters supplied to the Update Virtual Machine Extension operation.
  - api_version (String.t): Client Api Version.
  - subscription_id (String.t): Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Compute.Model.VirtualMachineExtension{}} on success
  {:error, info} on failure
  """
  @spec virtual_machine_extensions_update(Tesla.Env.client, String.t, String.t, String.t, Microsoft.Azure.Management.Compute.Model.VirtualMachineExtensionUpdate.t, String.t, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Compute.Model.VirtualMachineExtension.t} | {:error, Tesla.Env.t}
  def virtual_machine_extensions_update(connection, resource_group_name, vm_name, vm_extension_name, extension_parameters, api_version, subscription_id, _opts \\ []) do
    %{}
    |> method(:patch)
    |> url("/subscriptions/#{subscription_id}/resourceGroups/#{resource_group_name}/providers/Microsoft.Compute/virtualMachines/#{vm_name}/extensions/#{vm_extension_name}")
    |> add_param(:body, :body, extension_parameters)
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Compute.Model.VirtualMachineExtension{})
  end

  @doc """
  The operation to get all extensions of a Virtual Machine.

  ## Parameters

  - connection (Microsoft.Azure.Management.Compute.Connection): Connection to server
  - resource_group_name (String.t): The name of the resource group.
  - vm_name (String.t): The name of the virtual machine containing the extension.
  - api_version (String.t): Client Api Version.
  - subscription_id (String.t): Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
  - opts (KeywordList): [optional] Optional parameters
    - :__expand (String.t): The expand expression to apply on the operation.

  ## Returns

  {:ok, %Microsoft.Azure.Management.Compute.Model.VirtualMachineExtensionsListResult{}} on success
  {:error, info} on failure
  """
  @spec virtual_machines_get_extensions(Tesla.Env.client, String.t, String.t, String.t, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Compute.Model.VirtualMachineExtensionsListResult.t} | {:error, Tesla.Env.t}
  def virtual_machines_get_extensions(connection, resource_group_name, vm_name, api_version, subscription_id, opts \\ []) do
    optional_params = %{
      :"$expand" => :query
    }
    %{}
    |> method(:get)
    |> url("/subscriptions/#{subscription_id}/resourceGroups/#{resource_group_name}/providers/Microsoft.Compute/virtualMachines/#{vm_name}/extensions")
    |> add_param(:query, :"api-version", api_version)
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Compute.Model.VirtualMachineExtensionsListResult{})
  end
end
