# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Management.Model.ErrorResponse do
  @moduledoc """
  The error object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"error"
  ]

  @type t :: %__MODULE__{
    :"error" => ErrorDetails
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Management.Model.ErrorResponse do
  import Microsoft.Azure.Management.Management.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"error", :struct, Microsoft.Azure.Management.Management.Model.ErrorDetails, options)
  end
end

