# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Authorization.Model.ManagementLockProperties do
  @moduledoc """
  The lock properties.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"level",
    :"notes",
    :"owners"
  ]

  @type t :: %__MODULE__{
    :"level" => String.t,
    :"notes" => String.t,
    :"owners" => [ManagementLockOwner]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Authorization.Model.ManagementLockProperties do
  import Microsoft.Azure.Management.Authorization.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"owners", :list, Microsoft.Azure.Management.Authorization.Model.ManagementLockOwner, options)
  end
end

