# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Authorization.Model.ResourceType do
  @moduledoc """
  Resource Type
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"displayName",
    :"operations"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"displayName" => String.t,
    :"operations" => [ProviderOperation]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Authorization.Model.ResourceType do
  import Microsoft.Azure.Management.Authorization.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"operations", :list, Microsoft.Azure.Management.Authorization.Model.ProviderOperation, options)
  end
end

