# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Resources.Model.DeploymentExtended do
  @moduledoc """
  Deployment information.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"properties"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"name" => String.t,
    :"properties" => DeploymentPropertiesExtended
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Resources.Model.DeploymentExtended do
  import Microsoft.Azure.Management.Resources.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"properties", :struct, Microsoft.Azure.Management.Resources.Model.DeploymentPropertiesExtended, options)
  end
end

