# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Resources.Model.ExportTemplateRequest do
  @moduledoc """
  Export resource group template request parameters.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"resources",
    :"options"
  ]

  @type t :: %__MODULE__{
    :"resources" => [String.t],
    :"options" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Resources.Model.ExportTemplateRequest do
  def decode(value, _options) do
    value
  end
end

