# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Resources.Model.ResourceGroupProperties do
  @moduledoc """
  The resource group properties.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"provisioningState"
  ]

  @type t :: %__MODULE__{
    :"provisioningState" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Resources.Model.ResourceGroupProperties do
  def decode(value, _options) do
    value
  end
end

