# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.BootDiagnosticsInstanceView do
  @moduledoc """
  The instance view of a virtual machine boot diagnostics.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"consoleScreenshotBlobUri",
    :"serialConsoleLogBlobUri"
  ]

  @type t :: %__MODULE__{
    :"consoleScreenshotBlobUri" => String.t,
    :"serialConsoleLogBlobUri" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.BootDiagnosticsInstanceView do
  def decode(value, _options) do
    value
  end
end

