# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.CreationData do
  @moduledoc """
  Data used when creating a disk.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"createOption",
    :"storageAccountId",
    :"imageReference",
    :"sourceUri",
    :"sourceResourceId"
  ]

  @type t :: %__MODULE__{
    :"createOption" => String.t,
    :"storageAccountId" => String.t,
    :"imageReference" => ImageDiskReference,
    :"sourceUri" => String.t,
    :"sourceResourceId" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.CreationData do
  import Microsoft.Azure.Management.Compute.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"imageReference", :struct, Microsoft.Azure.Management.Compute.Model.ImageDiskReference, options)
  end
end

