# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.HardwareProfile do
  @moduledoc """
  Specifies the hardware settings for the virtual machine.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"vmSize"
  ]

  @type t :: %__MODULE__{
    :"vmSize" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.HardwareProfile do
  def decode(value, _options) do
    value
  end
end

