# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.ImageDiskReference do
  @moduledoc """
  The source image used for creating the disk.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"lun"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"lun" => integer()
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.ImageDiskReference do
  def decode(value, _options) do
    value
  end
end

