# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.ImageDataDisk do
  @moduledoc """
  Describes a data disk.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"lun",
    :"snapshot",
    :"managedDisk",
    :"blobUri",
    :"caching",
    :"diskSizeGB",
    :"storageAccountType"
  ]

  @type t :: %__MODULE__{
    :"lun" => integer(),
    :"snapshot" => SubResource,
    :"managedDisk" => SubResource,
    :"blobUri" => String.t,
    :"caching" => String.t,
    :"diskSizeGB" => integer(),
    :"storageAccountType" => StorageAccountType
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.ImageDataDisk do
  import Microsoft.Azure.Management.Compute.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"snapshot", :struct, Microsoft.Azure.Management.Compute.Model.SubResource, options)
    |> deserialize(:"managedDisk", :struct, Microsoft.Azure.Management.Compute.Model.SubResource, options)
    |> deserialize(:"storageAccountType", :struct, Microsoft.Azure.Management.Compute.Model.StorageAccountType, options)
  end
end

