# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.OsDiskImage do
  @moduledoc """
  Contains the os disk image information.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"operatingSystem"
  ]

  @type t :: %__MODULE__{
    :"operatingSystem" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.OsDiskImage do
  def decode(value, _options) do
    value
  end
end

