# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.ResourceSkuRestrictions do
  @moduledoc """
  Describes scaling information of a SKU.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"type",
    :"values",
    :"restrictionInfo",
    :"reasonCode"
  ]

  @type t :: %__MODULE__{
    :"type" => String.t,
    :"values" => [String.t],
    :"restrictionInfo" => ResourceSkuRestrictionInfo,
    :"reasonCode" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.ResourceSkuRestrictions do
  import Microsoft.Azure.Management.Compute.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"restrictionInfo", :struct, Microsoft.Azure.Management.Compute.Model.ResourceSkuRestrictionInfo, options)
  end
end

