# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.RollbackStatusInfo do
  @moduledoc """
  Information about rollback on failed VM instances after a OS Upgrade operation.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"successfullyRolledbackInstanceCount",
    :"failedRolledbackInstanceCount",
    :"rollbackError"
  ]

  @type t :: %__MODULE__{
    :"successfullyRolledbackInstanceCount" => integer(),
    :"failedRolledbackInstanceCount" => integer(),
    :"rollbackError" => ApiError
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.RollbackStatusInfo do
  import Microsoft.Azure.Management.Compute.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"rollbackError", :struct, Microsoft.Azure.Management.Compute.Model.ApiError, options)
  end
end

