# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.RollingUpgradePolicy do
  @moduledoc """
  The configuration parameters used while performing a rolling upgrade.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"maxBatchInstancePercent",
    :"maxUnhealthyInstancePercent",
    :"maxUnhealthyUpgradedInstancePercent",
    :"pauseTimeBetweenBatches"
  ]

  @type t :: %__MODULE__{
    :"maxBatchInstancePercent" => integer(),
    :"maxUnhealthyInstancePercent" => integer(),
    :"maxUnhealthyUpgradedInstancePercent" => integer(),
    :"pauseTimeBetweenBatches" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.RollingUpgradePolicy do
  def decode(value, _options) do
    value
  end
end

