# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.SnapshotUpdate do
  @moduledoc """
  Snapshot update resource.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"properties",
    :"tags",
    :"sku"
  ]

  @type t :: %__MODULE__{
    :"properties" => DiskUpdateProperties,
    :"tags" => %{optional(String.t) => String.t},
    :"sku" => SnapshotSku
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.SnapshotUpdate do
  import Microsoft.Azure.Management.Compute.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"properties", :struct, Microsoft.Azure.Management.Compute.Model.DiskUpdateProperties, options)
    |> deserialize(:"sku", :struct, Microsoft.Azure.Management.Compute.Model.SnapshotSku, options)
  end
end

