# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.UpgradeOperationHistoricalStatusInfoProperties do
  @moduledoc """
  Describes each OS upgrade on the Virtual Machine Scale Set.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"runningStatus",
    :"progress",
    :"error",
    :"startedBy",
    :"targetImageReference",
    :"rollbackInfo"
  ]

  @type t :: %__MODULE__{
    :"runningStatus" => UpgradeOperationHistoryStatus,
    :"progress" => RollingUpgradeProgressInfo,
    :"error" => ApiError,
    :"startedBy" => String.t,
    :"targetImageReference" => ImageReference,
    :"rollbackInfo" => RollbackStatusInfo
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.UpgradeOperationHistoricalStatusInfoProperties do
  import Microsoft.Azure.Management.Compute.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"runningStatus", :struct, Microsoft.Azure.Management.Compute.Model.UpgradeOperationHistoryStatus, options)
    |> deserialize(:"progress", :struct, Microsoft.Azure.Management.Compute.Model.RollingUpgradeProgressInfo, options)
    |> deserialize(:"error", :struct, Microsoft.Azure.Management.Compute.Model.ApiError, options)
    |> deserialize(:"targetImageReference", :struct, Microsoft.Azure.Management.Compute.Model.ImageReference, options)
    |> deserialize(:"rollbackInfo", :struct, Microsoft.Azure.Management.Compute.Model.RollbackStatusInfo, options)
  end
end

