# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.Usage do
  @moduledoc """
  Describes Compute Resource Usage.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"unit",
    :"currentValue",
    :"limit",
    :"name"
  ]

  @type t :: %__MODULE__{
    :"unit" => String.t,
    :"currentValue" => integer(),
    :"limit" => integer(),
    :"name" => UsageName
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.Usage do
  import Microsoft.Azure.Management.Compute.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"name", :struct, Microsoft.Azure.Management.Compute.Model.UsageName, options)
  end
end

