# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.VirtualMachineScaleSetVmProfile do
  @moduledoc """
  Describes a virtual machine scale set virtual machine profile.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"osProfile",
    :"storageProfile",
    :"networkProfile",
    :"diagnosticsProfile",
    :"extensionProfile",
    :"licenseType",
    :"priority",
    :"evictionPolicy"
  ]

  @type t :: %__MODULE__{
    :"osProfile" => VirtualMachineScaleSetOsProfile,
    :"storageProfile" => VirtualMachineScaleSetStorageProfile,
    :"networkProfile" => VirtualMachineScaleSetNetworkProfile,
    :"diagnosticsProfile" => DiagnosticsProfile,
    :"extensionProfile" => VirtualMachineScaleSetExtensionProfile,
    :"licenseType" => String.t,
    :"priority" => String.t,
    :"evictionPolicy" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.VirtualMachineScaleSetVmProfile do
  import Microsoft.Azure.Management.Compute.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"osProfile", :struct, Microsoft.Azure.Management.Compute.Model.VirtualMachineScaleSetOsProfile, options)
    |> deserialize(:"storageProfile", :struct, Microsoft.Azure.Management.Compute.Model.VirtualMachineScaleSetStorageProfile, options)
    |> deserialize(:"networkProfile", :struct, Microsoft.Azure.Management.Compute.Model.VirtualMachineScaleSetNetworkProfile, options)
    |> deserialize(:"diagnosticsProfile", :struct, Microsoft.Azure.Management.Compute.Model.DiagnosticsProfile, options)
    |> deserialize(:"extensionProfile", :struct, Microsoft.Azure.Management.Compute.Model.VirtualMachineScaleSetExtensionProfile, options)
  end
end

