# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.VirtualMachineHealthStatus do
  @moduledoc """
  The health status of the VM.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"status"
  ]

  @type t :: %__MODULE__{
    :"status" => InstanceViewStatus
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.VirtualMachineHealthStatus do
  import Microsoft.Azure.Management.Compute.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"status", :struct, Microsoft.Azure.Management.Compute.Model.InstanceViewStatus, options)
  end
end

