# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.VirtualMachineExtensionInstanceView do
  @moduledoc """
  The instance view of a virtual machine extension.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"type",
    :"typeHandlerVersion",
    :"substatuses",
    :"statuses"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"type" => String.t,
    :"typeHandlerVersion" => String.t,
    :"substatuses" => [InstanceViewStatus],
    :"statuses" => [InstanceViewStatus]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.VirtualMachineExtensionInstanceView do
  import Microsoft.Azure.Management.Compute.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"substatuses", :list, Microsoft.Azure.Management.Compute.Model.InstanceViewStatus, options)
    |> deserialize(:"statuses", :list, Microsoft.Azure.Management.Compute.Model.InstanceViewStatus, options)
  end
end

