# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.VirtualHardDisk do
  @moduledoc """
  Describes the uri of a disk.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"uri"
  ]

  @type t :: %__MODULE__{
    :"uri" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.VirtualHardDisk do
  def decode(value, _options) do
    value
  end
end

