# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.VirtualMachineImageProperties do
  @moduledoc """
  Describes the properties of a Virtual Machine Image.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"plan",
    :"osDiskImage",
    :"dataDiskImages"
  ]

  @type t :: %__MODULE__{
    :"plan" => PurchasePlan,
    :"osDiskImage" => OsDiskImage,
    :"dataDiskImages" => [DataDiskImage]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.VirtualMachineImageProperties do
  import Microsoft.Azure.Management.Compute.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"plan", :struct, Microsoft.Azure.Management.Compute.Model.PurchasePlan, options)
    |> deserialize(:"osDiskImage", :struct, Microsoft.Azure.Management.Compute.Model.OsDiskImage, options)
    |> deserialize(:"dataDiskImages", :list, Microsoft.Azure.Management.Compute.Model.DataDiskImage, options)
  end
end

