# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.VirtualMachineStatusCodeCount do
  @moduledoc """
  The status code and count of the virtual machine scale set instance view status summary.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"code",
    :"count"
  ]

  @type t :: %__MODULE__{
    :"code" => String.t,
    :"count" => integer()
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.VirtualMachineStatusCodeCount do
  def decode(value, _options) do
    value
  end
end

