# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Database.CosmosDb.Model.DatabaseAccountCreateUpdateProperties do
  @moduledoc """
  Properties to create and update Azure Cosmos DB database accounts.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"consistencyPolicy",
    :"locations",
    :"databaseAccountOfferType",
    :"ipRangeFilter",
    :"isVirtualNetworkFilterEnabled",
    :"enableAutomaticFailover",
    :"capabilities",
    :"virtualNetworkRules"
  ]

  @type t :: %__MODULE__{
    :"consistencyPolicy" => ConsistencyPolicy,
    :"locations" => [Location],
    :"databaseAccountOfferType" => DatabaseAccountOfferType,
    :"ipRangeFilter" => IpRangeFilter,
    :"isVirtualNetworkFilterEnabled" => boolean(),
    :"enableAutomaticFailover" => boolean(),
    :"capabilities" => [Capability],
    :"virtualNetworkRules" => [VirtualNetworkRule]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Database.CosmosDb.Model.DatabaseAccountCreateUpdateProperties do
  import Microsoft.Azure.Management.Database.CosmosDb.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"consistencyPolicy", :struct, Microsoft.Azure.Management.Database.CosmosDb.Model.ConsistencyPolicy, options)
    |> deserialize(:"locations", :list, Microsoft.Azure.Management.Database.CosmosDb.Model.Location, options)
    |> deserialize(:"databaseAccountOfferType", :struct, Microsoft.Azure.Management.Database.CosmosDb.Model.DatabaseAccountOfferType, options)
    |> deserialize(:"ipRangeFilter", :struct, Microsoft.Azure.Management.Database.CosmosDb.Model.IpRangeFilter, options)
    |> deserialize(:"capabilities", :list, Microsoft.Azure.Management.Database.CosmosDb.Model.Capability, options)
    |> deserialize(:"virtualNetworkRules", :list, Microsoft.Azure.Management.Database.CosmosDb.Model.VirtualNetworkRule, options)
  end
end

