# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Containers.Api.ContainerServices do
  @moduledoc """
  API calls for all endpoints tagged `ContainerServices`.
  """

  alias Microsoft.Azure.Management.Containers.Connection
  import Microsoft.Azure.Management.Containers.RequestBuilder


  @doc """
  Gets a list of container services in the specified subscription.
  Gets a list of container services in the specified subscription. The operation returns properties of each container service including state, orchestrator, number of masters and agents, and FQDNs of masters and agents.

  ## Parameters

  - connection (Microsoft.Azure.Management.Containers.Connection): Connection to server
  - api_version (String.t): Client Api Version.
  - subscription_id (String.t): Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Containers.Model.ContainerServiceListResult{}} on success
  {:error, info} on failure
  """
  @spec container_services_list(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Containers.Model.ContainerServiceListResult.t} | {:error, Tesla.Env.t}
  def container_services_list(connection, api_version, subscription_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/subscriptions/#{subscription_id}/providers/Microsoft.ContainerService/containerServices")
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Containers.Model.ContainerServiceListResult{})
  end

  @doc """
  Gets a list of container services in the specified resource group.
  Gets a list of container services in the specified subscription and resource group. The operation returns properties of each container service including state, orchestrator, number of masters and agents, and FQDNs of masters and agents.

  ## Parameters

  - connection (Microsoft.Azure.Management.Containers.Connection): Connection to server
  - resource_group_name (String.t): The name of the resource group.
  - api_version (String.t): Client Api Version.
  - subscription_id (String.t): Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Containers.Model.ContainerServiceListResult{}} on success
  {:error, info} on failure
  """
  @spec container_services_list_by_resource_group(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Containers.Model.ContainerServiceListResult.t} | {:error, Tesla.Env.t}
  def container_services_list_by_resource_group(connection, resource_group_name, api_version, subscription_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/subscriptions/#{subscription_id}/resourceGroups/#{resource_group_name}/providers/Microsoft.ContainerService/containerServices")
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Containers.Model.ContainerServiceListResult{})
  end
end
