# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Subscription.Model.SubscriptionCreationParameters do
  @moduledoc """
  Subscription Creation Parameters required to create a new Azure subscription.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"displayName",
    :"owners",
    :"offerType",
    :"additionalParameters"
  ]

  @type t :: %__MODULE__{
    :"displayName" => String.t,
    :"owners" => [AdPrincipal],
    :"offerType" => String.t,
    :"additionalParameters" => %{optional(String.t) => Object}
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Subscription.Model.SubscriptionCreationParameters do
  import Microsoft.Azure.Management.Subscription.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"owners", :list, Microsoft.Azure.Management.Subscription.Model.AdPrincipal, options)
    |> deserialize(:"additionalParameters", :map, Microsoft.Azure.Management.Subscription.Model.Object, options)
  end
end

