# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Subscription.Model.SubscriptionDefinition do
  @moduledoc """
  The subscription definition used to create the subscription.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"type",
    :"properties"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"name" => String.t,
    :"type" => String.t,
    :"properties" => SubscriptionDefinitionProperties
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Subscription.Model.SubscriptionDefinition do
  import Microsoft.Azure.Management.Subscription.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"properties", :struct, Microsoft.Azure.Management.Subscription.Model.SubscriptionDefinitionProperties, options)
  end
end

