# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Authorization.Model.RoleDefinitionProperties do
  @moduledoc """
  Role definition properties.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"roleName",
    :"description",
    :"type",
    :"permissions",
    :"assignableScopes"
  ]

  @type t :: %__MODULE__{
    :"roleName" => String.t,
    :"description" => String.t,
    :"type" => String.t,
    :"permissions" => [Permission],
    :"assignableScopes" => [String.t]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Authorization.Model.RoleDefinitionProperties do
  import Microsoft.Azure.Management.Authorization.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"permissions", :list, Microsoft.Azure.Management.Authorization.Model.Permission, options)
  end
end

