# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Api.VirtualMachineSizes do
  @moduledoc """
  API calls for all endpoints tagged `VirtualMachineSizes`.
  """

  alias Microsoft.Azure.Management.Compute.Connection
  import Microsoft.Azure.Management.Compute.RequestBuilder


  @doc """
  Lists all available virtual machine sizes for a subscription in a location.

  ## Parameters

  - connection (Microsoft.Azure.Management.Compute.Connection): Connection to server
  - location (String.t): The location upon which virtual-machine-sizes is queried.
  - api_version (String.t): Client Api Version.
  - subscription_id (String.t): Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Compute.Model.VirtualMachineSizeListResult{}} on success
  {:error, info} on failure
  """
  @spec virtual_machine_sizes_list(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Compute.Model.VirtualMachineSizeListResult.t} | {:error, Tesla.Env.t}
  def virtual_machine_sizes_list(connection, location, api_version, subscription_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/subscriptions/#{subscription_id}/providers/Microsoft.Compute/locations/#{location}/vmSizes")
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Compute.Model.VirtualMachineSizeListResult{})
  end
end
