# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Preview.BotService.Model.BotResponseList do
  @moduledoc """
  The list of  bot service operation response.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"nextLink",
    :"value"
  ]

  @type t :: %__MODULE__{
    :"nextLink" => String.t,
    :"value" => [Bot]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Preview.BotService.Model.BotResponseList do
  import Microsoft.Azure.Management.Preview.BotService.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"value", :list, Microsoft.Azure.Management.Preview.BotService.Model.Bot, options)
  end
end

