# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Preview.BotService.Model.FacebookChannelProperties do
  @moduledoc """
  The parameters to provide for the Facebook channel.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"verifyToken",
    :"pages",
    :"appId",
    :"appSecret",
    :"callbackUrl",
    :"isEnabled"
  ]

  @type t :: %__MODULE__{
    :"verifyToken" => String.t,
    :"pages" => [FacebookPage],
    :"appId" => String.t,
    :"appSecret" => String.t,
    :"callbackUrl" => String.t,
    :"isEnabled" => boolean()
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Preview.BotService.Model.FacebookChannelProperties do
  import Microsoft.Azure.Management.Preview.BotService.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"pages", :list, Microsoft.Azure.Management.Preview.BotService.Model.FacebookPage, options)
  end
end

