# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Preview.BotService.Model.MsTeamsChannel do
  @moduledoc """
  Microsoft Teams channel definition
  """

  @derive [Poison.Encoder]
  defstruct [
    :"channelName"
  ]

  @type t :: %__MODULE__{
    :"channelName" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Preview.BotService.Model.MsTeamsChannel do
  def decode(value, _options) do
    value
  end
end

