# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Preview.BotService.Model.ServiceProvider do
  @moduledoc """
  Service Provider Definition
  """

  @derive [Poison.Encoder]
  defstruct [
    :"properties"
  ]

  @type t :: %__MODULE__{
    :"properties" => ServiceProviderProperties
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Preview.BotService.Model.ServiceProvider do
  import Microsoft.Azure.Management.Preview.BotService.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"properties", :struct, Microsoft.Azure.Management.Preview.BotService.Model.ServiceProviderProperties, options)
  end
end

