# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Preview.BotService.Model.SkypeChannelProperties do
  @moduledoc """
  The parameters to provide for the Microsoft Teams channel.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"enableMessaging",
    :"enableMediaCards",
    :"enableVideo",
    :"enableCalling",
    :"enableScreenSharing",
    :"enableGroups",
    :"groupsMode",
    :"callingWebHook",
    :"isEnabled"
  ]

  @type t :: %__MODULE__{
    :"enableMessaging" => boolean(),
    :"enableMediaCards" => boolean(),
    :"enableVideo" => boolean(),
    :"enableCalling" => boolean(),
    :"enableScreenSharing" => boolean(),
    :"enableGroups" => boolean(),
    :"groupsMode" => String.t,
    :"callingWebHook" => String.t,
    :"isEnabled" => boolean()
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Preview.BotService.Model.SkypeChannelProperties do
  def decode(value, _options) do
    value
  end
end

