# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Preview.BotService.Model.SlackChannelProperties do
  @moduledoc """
  The parameters to provide for the Slack channel.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"clientId",
    :"clientSecret",
    :"verificationToken",
    :"landingPageUrl",
    :"redirectAction",
    :"lastSubmissionId",
    :"registerBeforeOAuthFlow",
    :"isValidated",
    :"isEnabled"
  ]

  @type t :: %__MODULE__{
    :"clientId" => String.t,
    :"clientSecret" => String.t,
    :"verificationToken" => String.t,
    :"landingPageUrl" => String.t,
    :"redirectAction" => String.t,
    :"lastSubmissionId" => String.t,
    :"registerBeforeOAuthFlow" => boolean(),
    :"isValidated" => boolean(),
    :"isEnabled" => boolean()
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Preview.BotService.Model.SlackChannelProperties do
  def decode(value, _options) do
    value
  end
end

