# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Preview.EventHub.Api.EventHubsClusters do
  @moduledoc """
  API calls for all endpoints tagged `EventHubsClusters`.
  """

  alias Microsoft.Azure.Management.Preview.EventHub.Connection
  import Microsoft.Azure.Management.Preview.EventHub.RequestBuilder


  @doc """
  Lists the available Event Hubs Clusters within an ARM resource group.

  ## Parameters

  - connection (Microsoft.Azure.Management.Preview.EventHub.Connection): Connection to server
  - subscription_id (String.t): Subscription credentials that uniquely identify a Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
  - resource_group_name (String.t): Name of the resource group within the Azure subscription.
  - api_version (String.t): Client API version.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Preview.EventHub.Model.ClusterListResult{}} on success
  {:error, info} on failure
  """
  @spec clusters_list_by_resource_group(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Preview.EventHub.Model.ClusterListResult.t} | {:error, Tesla.Env.t}
  def clusters_list_by_resource_group(connection, subscription_id, resource_group_name, api_version, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/subscriptions/#{subscription_id}/resourceGroups/#{resource_group_name}/providers/Microsoft.EventHub/clusters")
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Preview.EventHub.Model.ClusterListResult{})
  end
end
