# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.BootDiagnostics do
  @moduledoc """
  Boot Diagnostics is a debugging feature which allows you to view Console Output and Screenshot to diagnose VM status. &lt;br&gt;&lt;br&gt; For Linux Virtual Machines, you can easily view the output of your console log. &lt;br&gt;&lt;br&gt; For both Windows and Linux virtual machines, Azure also enables you to see a screenshot of the VM from the hypervisor.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"enabled",
    :"storageUri"
  ]

  @type t :: %__MODULE__{
    :"enabled" => boolean(),
    :"storageUri" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.BootDiagnostics do
  def decode(value, _options) do
    value
  end
end

