# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.DiskInstanceView do
  @moduledoc """
  The instance view of the disk.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"encryptionSettings",
    :"statuses"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"encryptionSettings" => [DiskEncryptionSettings],
    :"statuses" => [InstanceViewStatus]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.DiskInstanceView do
  import Microsoft.Azure.Management.Compute.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"encryptionSettings", :list, Microsoft.Azure.Management.Compute.Model.DiskEncryptionSettings, options)
    |> deserialize(:"statuses", :list, Microsoft.Azure.Management.Compute.Model.InstanceViewStatus, options)
  end
end

