# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.NetworkProfile do
  @moduledoc """
  Specifies the network interfaces of the virtual machine.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"networkInterfaces"
  ]

  @type t :: %__MODULE__{
    :"networkInterfaces" => [NetworkInterfaceReference]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.NetworkProfile do
  import Microsoft.Azure.Management.Compute.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"networkInterfaces", :list, Microsoft.Azure.Management.Compute.Model.NetworkInterfaceReference, options)
  end
end

