# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.VaultSecretGroup do
  @moduledoc """
  Describes a set of certificates which are all in the same Key Vault.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"sourceVault",
    :"vaultCertificates"
  ]

  @type t :: %__MODULE__{
    :"sourceVault" => SubResource,
    :"vaultCertificates" => [VaultCertificate]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.VaultSecretGroup do
  import Microsoft.Azure.Management.Compute.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"sourceVault", :struct, Microsoft.Azure.Management.Compute.Model.SubResource, options)
    |> deserialize(:"vaultCertificates", :list, Microsoft.Azure.Management.Compute.Model.VaultCertificate, options)
  end
end

