# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.VaultCertificate do
  @moduledoc """
  Describes a single certificate reference in a Key Vault, and where the certificate should reside on the VM.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"certificateUrl",
    :"certificateStore"
  ]

  @type t :: %__MODULE__{
    :"certificateUrl" => String.t,
    :"certificateStore" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.VaultCertificate do
  def decode(value, _options) do
    value
  end
end

