# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.VirtualMachineScaleSetUpdateStorageProfile do
  @moduledoc """
  Describes a virtual machine scale set storage profile.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"imageReference",
    :"osDisk",
    :"dataDisks"
  ]

  @type t :: %__MODULE__{
    :"imageReference" => ImageReference,
    :"osDisk" => VirtualMachineScaleSetUpdateOsDisk,
    :"dataDisks" => [VirtualMachineScaleSetDataDisk]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.VirtualMachineScaleSetUpdateStorageProfile do
  import Microsoft.Azure.Management.Compute.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"imageReference", :struct, Microsoft.Azure.Management.Compute.Model.ImageReference, options)
    |> deserialize(:"osDisk", :struct, Microsoft.Azure.Management.Compute.Model.VirtualMachineScaleSetUpdateOsDisk, options)
    |> deserialize(:"dataDisks", :list, Microsoft.Azure.Management.Compute.Model.VirtualMachineScaleSetDataDisk, options)
  end
end

