# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.VirtualMachineScaleSetIdentity do
  @moduledoc """
  Identity for the virtual machine scale set.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"principalId",
    :"tenantId",
    :"type",
    :"identityIds"
  ]

  @type t :: %__MODULE__{
    :"principalId" => String.t,
    :"tenantId" => String.t,
    :"type" => String.t,
    :"identityIds" => [String.t]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.VirtualMachineScaleSetIdentity do
  def decode(value, _options) do
    value
  end
end

