# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.VirtualMachineScaleSetDataDisk do
  @moduledoc """
  Describes a virtual machine scale set data disk.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"lun",
    :"caching",
    :"writeAcceleratorEnabled",
    :"createOption",
    :"diskSizeGB",
    :"managedDisk"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"lun" => integer(),
    :"caching" => Caching,
    :"writeAcceleratorEnabled" => boolean(),
    :"createOption" => CreateOption,
    :"diskSizeGB" => integer(),
    :"managedDisk" => VirtualMachineScaleSetManagedDiskParameters
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.VirtualMachineScaleSetDataDisk do
  import Microsoft.Azure.Management.Compute.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"caching", :struct, Microsoft.Azure.Management.Compute.Model.Caching, options)
    |> deserialize(:"createOption", :struct, Microsoft.Azure.Management.Compute.Model.CreateOption, options)
    |> deserialize(:"managedDisk", :struct, Microsoft.Azure.Management.Compute.Model.VirtualMachineScaleSetManagedDiskParameters, options)
  end
end

