# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Compute.Model.VirtualMachineScaleSetUpdate do
  @moduledoc """
  Describes a Virtual Machine Scale Set.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"tags"
  ]

  @type t :: %__MODULE__{
    :"tags" => %{optional(String.t) => String.t}
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Compute.Model.VirtualMachineScaleSetUpdate do
  def decode(value, _options) do
    value
  end
end

