# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Solutions.Model.ApplicationPropertiesPatchable do
  @moduledoc """
  The managed application properties.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"managedResourceGroupId",
    :"applicationDefinitionId",
    :"parameters",
    :"outputs",
    :"provisioningState",
    :"uiDefinitionUri"
  ]

  @type t :: %__MODULE__{
    :"managedResourceGroupId" => String.t,
    :"applicationDefinitionId" => String.t,
    :"parameters" => Object,
    :"outputs" => Object,
    :"provisioningState" => ProvisioningState,
    :"uiDefinitionUri" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Solutions.Model.ApplicationPropertiesPatchable do
  import Microsoft.Azure.Management.Solutions.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"parameters", :struct, Microsoft.Azure.Management.Solutions.Model.Object, options)
    |> deserialize(:"outputs", :struct, Microsoft.Azure.Management.Solutions.Model.Object, options)
    |> deserialize(:"provisioningState", :struct, Microsoft.Azure.Management.Solutions.Model.ProvisioningState, options)
  end
end

