# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Solutions.Model.ErrorResponse do
  @moduledoc """
  Error reponse indicates managed application is not able to process the incoming request. The reason is provided in the error message.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"httpStatus",
    :"errorCode",
    :"errorMessage"
  ]

  @type t :: %__MODULE__{
    :"httpStatus" => String.t,
    :"errorCode" => String.t,
    :"errorMessage" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Solutions.Model.ErrorResponse do
  def decode(value, _options) do
    value
  end
end

