# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Solutions.Model.Sku do
  @moduledoc """
  SKU for the resource.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"tier",
    :"size",
    :"family",
    :"model",
    :"capacity"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"tier" => String.t,
    :"size" => String.t,
    :"family" => String.t,
    :"model" => String.t,
    :"capacity" => integer()
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Solutions.Model.Sku do
  def decode(value, _options) do
    value
  end
end

