# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Preview.Subscription.Api.Default do
  @moduledoc """
  API calls for all endpoints tagged `Default`.
  """

  alias Microsoft.Azure.Management.Preview.Subscription.Connection
  import Microsoft.Azure.Management.Preview.Subscription.RequestBuilder


  @doc """
  Lists all of the available Microsoft.Subscription API operations.

  ## Parameters

  - connection (Microsoft.Azure.Management.Preview.Subscription.Connection): Connection to server
  - api_version (String.t): Version of the API to be used with the client request. Current version is 2015-06-01
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Preview.Subscription.Model.OperationListResult{}} on success
  {:error, info} on failure
  """
  @spec operations_list(Tesla.Env.client, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Preview.Subscription.Model.OperationListResult.t} | {:error, Tesla.Env.t}
  def operations_list(connection, api_version, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/providers/Microsoft.Subscription/operations")
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Preview.Subscription.Model.OperationListResult{})
  end

  @doc """
  Creates an Azure subscription

  ## Parameters

  - connection (Microsoft.Azure.Management.Preview.Subscription.Connection): Connection to server
  - enrollment_account_name (String.t): The name of the enrollment account to which the subscription will be billed.
  - api_version (String.t): Version of the API to be used with the client request. Current version is 2015-06-01
  - body (SubscriptionCreationParameters): The subscription creation parameters.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Preview.Subscription.Model.SubscriptionCreationResult{}} on success
  {:error, info} on failure
  """
  @spec subscription_factory_create_subscription_in_enrollment_account(Tesla.Env.client, String.t, String.t, Microsoft.Azure.Management.Preview.Subscription.Model.SubscriptionCreationParameters.t, keyword()) :: {:ok, Microsoft.Azure.Management.Preview.Subscription.Model.SubscriptionCreationResult.t} | {:error, Tesla.Env.t}
  def subscription_factory_create_subscription_in_enrollment_account(connection, enrollment_account_name, api_version, body, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/providers/Microsoft.Billing/enrollmentAccounts/#{enrollment_account_name}/providers/Microsoft.Subscription/createSubscription")
    |> add_param(:query, :"api-version", api_version)
    |> add_param(:body, :body, body)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Preview.Subscription.Model.SubscriptionCreationResult{})
  end

  @doc """
  Lists all of the available pending Microsoft.Subscription API operations.

  ## Parameters

  - connection (Microsoft.Azure.Management.Preview.Subscription.Connection): Connection to server
  - api_version (String.t): Version of the API to be used with the client request. Current version is 2015-06-01
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Preview.Subscription.Model.SubscriptionOperationListResult{}} on success
  {:error, info} on failure
  """
  @spec subscription_operations_list(Tesla.Env.client, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Preview.Subscription.Model.SubscriptionOperationListResult.t} | {:error, Tesla.Env.t}
  def subscription_operations_list(connection, api_version, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/providers/Microsoft.Subscription/subscriptionOperations")
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Preview.Subscription.Model.SubscriptionOperationListResult{})
  end
end
