# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Containers.Model.ContainerServiceVmDiagnostics do
  @moduledoc """
  Profile for diagnostics on the container service VMs.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"enabled",
    :"storageUri"
  ]

  @type t :: %__MODULE__{
    :"enabled" => boolean(),
    :"storageUri" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Containers.Model.ContainerServiceVmDiagnostics do
  def decode(value, _options) do
    value
  end
end

