# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Containers.Model.ContainerProperties do
  @moduledoc """
  The container instance properties.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"image",
    :"command",
    :"ports",
    :"environmentVariables",
    :"instanceView",
    :"resources",
    :"volumeMounts"
  ]

  @type t :: %__MODULE__{
    :"image" => String.t,
    :"command" => [String.t],
    :"ports" => [ContainerPort],
    :"environmentVariables" => [EnvironmentVariable],
    :"instanceView" => ContainerPropertiesInstanceView,
    :"resources" => ResourceRequirements,
    :"volumeMounts" => [VolumeMount]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Containers.Model.ContainerProperties do
  import Microsoft.Azure.Management.Containers.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ports", :list, Microsoft.Azure.Management.Containers.Model.ContainerPort, options)
    |> deserialize(:"environmentVariables", :list, Microsoft.Azure.Management.Containers.Model.EnvironmentVariable, options)
    |> deserialize(:"instanceView", :struct, Microsoft.Azure.Management.Containers.Model.ContainerPropertiesInstanceView, options)
    |> deserialize(:"resources", :struct, Microsoft.Azure.Management.Containers.Model.ResourceRequirements, options)
    |> deserialize(:"volumeMounts", :list, Microsoft.Azure.Management.Containers.Model.VolumeMount, options)
  end
end

