# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Containers.Model.ContainerServiceServicePrincipalProfile do
  @moduledoc """
  Information about a service principal identity for the cluster to use for manipulating Azure APIs. Either secret or keyVaultSecretRef must be specified.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"clientId",
    :"secret",
    :"keyVaultSecretRef"
  ]

  @type t :: %__MODULE__{
    :"clientId" => String.t,
    :"secret" => String.t,
    :"keyVaultSecretRef" => KeyVaultSecretRef
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Containers.Model.ContainerServiceServicePrincipalProfile do
  import Microsoft.Azure.Management.Containers.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"keyVaultSecretRef", :struct, Microsoft.Azure.Management.Containers.Model.KeyVaultSecretRef, options)
  end
end

