# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Containers.Model.ContainerServiceAgentPoolProfile do
  @moduledoc """
  Profile for the container service agent pool.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"count",
    :"vmSize",
    :"osDiskSizeGB",
    :"dnsPrefix",
    :"fqdn",
    :"ports",
    :"storageProfile",
    :"vnetSubnetID",
    :"osType"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"count" => integer(),
    :"vmSize" => ContainerServiceVmSize,
    :"osDiskSizeGB" => ContainerServiceOsDisk,
    :"dnsPrefix" => String.t,
    :"fqdn" => String.t,
    :"ports" => [integer()],
    :"storageProfile" => ContainerServiceStorageProfile,
    :"vnetSubnetID" => ContainerServiceVnetSubnetId,
    :"osType" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Containers.Model.ContainerServiceAgentPoolProfile do
  import Microsoft.Azure.Management.Containers.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"vmSize", :struct, Microsoft.Azure.Management.Containers.Model.ContainerServiceVmSize, options)
    |> deserialize(:"osDiskSizeGB", :struct, Microsoft.Azure.Management.Containers.Model.ContainerServiceOsDisk, options)
    |> deserialize(:"storageProfile", :struct, Microsoft.Azure.Management.Containers.Model.ContainerServiceStorageProfile, options)
    |> deserialize(:"vnetSubnetID", :struct, Microsoft.Azure.Management.Containers.Model.ContainerServiceVnetSubnetId, options)
  end
end

