# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Containers.Model.ContainerServiceWindowsProfile do
  @moduledoc """
  Profile for Windows VMs in the container service cluster.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"adminUsername",
    :"adminPassword"
  ]

  @type t :: %__MODULE__{
    :"adminUsername" => String.t,
    :"adminPassword" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Containers.Model.ContainerServiceWindowsProfile do
  def decode(value, _options) do
    value
  end
end

