# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Containers.Model.ManagedClusterPoolUpgradeProfile do
  @moduledoc """
  The list of available upgrade versions.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"kubernetesVersion",
    :"name",
    :"osType",
    :"upgrades"
  ]

  @type t :: %__MODULE__{
    :"kubernetesVersion" => String.t,
    :"name" => String.t,
    :"osType" => OsType,
    :"upgrades" => [String.t]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Containers.Model.ManagedClusterPoolUpgradeProfile do
  import Microsoft.Azure.Management.Containers.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"osType", :struct, Microsoft.Azure.Management.Containers.Model.OsType, options)
  end
end

