# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Containers.Model.ManagedClusterProperties do
  @moduledoc """
  Properties of the managed cluster.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"provisioningState",
    :"dnsPrefix",
    :"fqdn",
    :"kubernetesVersion",
    :"agentPoolProfiles",
    :"linuxProfile",
    :"servicePrincipalProfile"
  ]

  @type t :: %__MODULE__{
    :"provisioningState" => String.t,
    :"dnsPrefix" => String.t,
    :"fqdn" => String.t,
    :"kubernetesVersion" => String.t,
    :"agentPoolProfiles" => [ContainerServiceAgentPoolProfile],
    :"linuxProfile" => ContainerServiceLinuxProfile,
    :"servicePrincipalProfile" => ContainerServiceServicePrincipalProfile
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Containers.Model.ManagedClusterProperties do
  import Microsoft.Azure.Management.Containers.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"agentPoolProfiles", :list, Microsoft.Azure.Management.Containers.Model.ContainerServiceAgentPoolProfile, options)
    |> deserialize(:"linuxProfile", :struct, Microsoft.Azure.Management.Containers.Model.ContainerServiceLinuxProfile, options)
    |> deserialize(:"servicePrincipalProfile", :struct, Microsoft.Azure.Management.Containers.Model.ContainerServiceServicePrincipalProfile, options)
  end
end

