# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Containers.Model.OperationServiceSpecificationDefinition do
  @moduledoc """
  The definition of Azure Monitoring metrics list.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"metricSpecifications"
  ]

  @type t :: %__MODULE__{
    :"metricSpecifications" => [OperationMetricSpecificationDefinition]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Containers.Model.OperationServiceSpecificationDefinition do
  import Microsoft.Azure.Management.Containers.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"metricSpecifications", :list, Microsoft.Azure.Management.Containers.Model.OperationMetricSpecificationDefinition, options)
  end
end

