# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Containers.Model.OrchestratorVersionProfileProperties do
  @moduledoc """
  The properties of an orchestrator version profile.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"orchestrators"
  ]

  @type t :: %__MODULE__{
    :"orchestrators" => [OrchestratorVersionProfile]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Containers.Model.OrchestratorVersionProfileProperties do
  import Microsoft.Azure.Management.Containers.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"orchestrators", :list, Microsoft.Azure.Management.Containers.Model.OrchestratorVersionProfile, options)
  end
end

