# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Containers.Model.OrchestratorVersionProfile do
  @moduledoc """
  The profile of an orchestrator and its available versions.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"orchestratorType",
    :"orchestratorVersion",
    :"default",
    :"upgrades"
  ]

  @type t :: %__MODULE__{
    :"orchestratorType" => String.t,
    :"orchestratorVersion" => String.t,
    :"default" => boolean(),
    :"upgrades" => [OrchestratorProfile]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Containers.Model.OrchestratorVersionProfile do
  import Microsoft.Azure.Management.Containers.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"upgrades", :list, Microsoft.Azure.Management.Containers.Model.OrchestratorProfile, options)
  end
end

