# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Containers.Model.RegistryPropertiesUpdateParameters do
  @moduledoc """
  The parameters for updating the properties of a container registry.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"adminUserEnabled",
    :"storageAccount"
  ]

  @type t :: %__MODULE__{
    :"adminUserEnabled" => boolean(),
    :"storageAccount" => StorageAccountProperties
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Containers.Model.RegistryPropertiesUpdateParameters do
  import Microsoft.Azure.Management.Containers.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"storageAccount", :struct, Microsoft.Azure.Management.Containers.Model.StorageAccountProperties, options)
  end
end

