# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Containers.Model.WebhookProperties do
  @moduledoc """
  The properties of a webhook.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"status",
    :"scope",
    :"actions",
    :"provisioningState"
  ]

  @type t :: %__MODULE__{
    :"status" => String.t,
    :"scope" => String.t,
    :"actions" => [String.t],
    :"provisioningState" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Containers.Model.WebhookProperties do
  def decode(value, _options) do
    value
  end
end

