# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.DbForMysql.Model.ServerPropertiesForCreate do
  @moduledoc """
  The properties used to create a new server.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"version",
    :"sslEnforcement",
    :"storageProfile",
    :"createMode"
  ]

  @type t :: %__MODULE__{
    :"version" => ServerVersion,
    :"sslEnforcement" => SslEnforcement,
    :"storageProfile" => StorageProfile,
    :"createMode" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.DbForMysql.Model.ServerPropertiesForCreate do
  import Microsoft.Azure.Management.DbForMysql.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"version", :struct, Microsoft.Azure.Management.DbForMysql.Model.ServerVersion, options)
    |> deserialize(:"sslEnforcement", :struct, Microsoft.Azure.Management.DbForMysql.Model.SslEnforcement, options)
    |> deserialize(:"storageProfile", :struct, Microsoft.Azure.Management.DbForMysql.Model.StorageProfile, options)
  end
end

