# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Storage.Model.Encryption do
  @moduledoc """
  The encryption settings on the storage account.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"services",
    :"keySource",
    :"keyvaultproperties"
  ]

  @type t :: %__MODULE__{
    :"services" => EncryptionServices,
    :"keySource" => String.t,
    :"keyvaultproperties" => KeyVaultProperties
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Storage.Model.Encryption do
  import Microsoft.Azure.Management.Storage.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"services", :struct, Microsoft.Azure.Management.Storage.Model.EncryptionServices, options)
    |> deserialize(:"keyvaultproperties", :struct, Microsoft.Azure.Management.Storage.Model.KeyVaultProperties, options)
  end
end

