# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Storage.Model.ImmutabilityPolicyProperty do
  @moduledoc """
  The properties of an ImmutabilityPolicy of a blob container.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"immutabilityPeriodSinceCreationInDays",
    :"state"
  ]

  @type t :: %__MODULE__{
    :"immutabilityPeriodSinceCreationInDays" => integer(),
    :"state" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Storage.Model.ImmutabilityPolicyProperty do
  def decode(value, _options) do
    value
  end
end

