# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Storage.Model.ListAccountSasResponse do
  @moduledoc """
  The List SAS credentials operation response.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountSasToken"
  ]

  @type t :: %__MODULE__{
    :"accountSasToken" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Storage.Model.ListAccountSasResponse do
  def decode(value, _options) do
    value
  end
end

