# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Storage.Model.ListContainerItems do
  @moduledoc """
  The list of blob containers.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"value"
  ]

  @type t :: %__MODULE__{
    :"value" => [ListContainerItem]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Storage.Model.ListContainerItems do
  import Microsoft.Azure.Management.Storage.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"value", :list, Microsoft.Azure.Management.Storage.Model.ListContainerItem, options)
  end
end

