# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Storage.Model.MetricSpecification do
  @moduledoc """
  Metric specification of operation.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"displayName",
    :"displayDescription",
    :"unit",
    :"dimensions",
    :"aggregationType",
    :"fillGapWithZero",
    :"category",
    :"resourceIdDimensionNameOverride"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"displayName" => String.t,
    :"displayDescription" => String.t,
    :"unit" => String.t,
    :"dimensions" => [Dimension],
    :"aggregationType" => String.t,
    :"fillGapWithZero" => boolean(),
    :"category" => String.t,
    :"resourceIdDimensionNameOverride" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Storage.Model.MetricSpecification do
  import Microsoft.Azure.Management.Storage.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"dimensions", :list, Microsoft.Azure.Management.Storage.Model.Dimension, options)
  end
end

