# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Storage.Model.ServiceSasParameters do
  @moduledoc """
  The parameters to list service SAS credentials of a speicific resource.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"canonicalizedResource",
    :"signedResource",
    :"signedPermission",
    :"signedIp",
    :"signedProtocol",
    :"signedStart",
    :"signedExpiry",
    :"signedIdentifier",
    :"startPk",
    :"endPk",
    :"startRk",
    :"endRk",
    :"keyToSign",
    :"rscc",
    :"rscd",
    :"rsce",
    :"rscl",
    :"rsct"
  ]

  @type t :: %__MODULE__{
    :"canonicalizedResource" => String.t,
    :"signedResource" => String.t,
    :"signedPermission" => String.t,
    :"signedIp" => String.t,
    :"signedProtocol" => String.t,
    :"signedStart" => DateTime.t,
    :"signedExpiry" => DateTime.t,
    :"signedIdentifier" => String.t,
    :"startPk" => String.t,
    :"endPk" => String.t,
    :"startRk" => String.t,
    :"endRk" => String.t,
    :"keyToSign" => String.t,
    :"rscc" => String.t,
    :"rscd" => String.t,
    :"rsce" => String.t,
    :"rscl" => String.t,
    :"rsct" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Storage.Model.ServiceSasParameters do
  def decode(value, _options) do
    value
  end
end

