# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Storage.Model.ServiceSpecification do
  @moduledoc """
  One property of operation, include metric specifications.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"metricSpecifications"
  ]

  @type t :: %__MODULE__{
    :"metricSpecifications" => [MetricSpecification]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Storage.Model.ServiceSpecification do
  import Microsoft.Azure.Management.Storage.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"metricSpecifications", :list, Microsoft.Azure.Management.Storage.Model.MetricSpecification, options)
  end
end

