# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Storage.Model.StorageAccountCreateParameters do
  @moduledoc """
  The parameters used when creating a storage account.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"sku",
    :"kind",
    :"location",
    :"tags",
    :"identity",
    :"properties"
  ]

  @type t :: %__MODULE__{
    :"sku" => Sku,
    :"kind" => String.t,
    :"location" => String.t,
    :"tags" => %{optional(String.t) => String.t},
    :"identity" => Identity,
    :"properties" => StorageAccountPropertiesCreateParameters
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Storage.Model.StorageAccountCreateParameters do
  import Microsoft.Azure.Management.Storage.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"sku", :struct, Microsoft.Azure.Management.Storage.Model.Sku, options)
    |> deserialize(:"identity", :struct, Microsoft.Azure.Management.Storage.Model.Identity, options)
    |> deserialize(:"properties", :struct, Microsoft.Azure.Management.Storage.Model.StorageAccountPropertiesCreateParameters, options)
  end
end

