# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Storage.Model.StorageAccountPropertiesUpdateParameters do
  @moduledoc """
  The parameters used when updating a storage account.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"customDomain",
    :"encryption",
    :"accessTier",
    :"supportsHttpsTrafficOnly",
    :"networkAcls"
  ]

  @type t :: %__MODULE__{
    :"customDomain" => CustomDomain,
    :"encryption" => Encryption,
    :"accessTier" => String.t,
    :"supportsHttpsTrafficOnly" => boolean(),
    :"networkAcls" => NetworkRuleSet
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Storage.Model.StorageAccountPropertiesUpdateParameters do
  import Microsoft.Azure.Management.Storage.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"customDomain", :struct, Microsoft.Azure.Management.Storage.Model.CustomDomain, options)
    |> deserialize(:"encryption", :struct, Microsoft.Azure.Management.Storage.Model.Encryption, options)
    |> deserialize(:"networkAcls", :struct, Microsoft.Azure.Management.Storage.Model.NetworkRuleSet, options)
  end
end

