# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Storage.Model.StorageAccountKey do
  @moduledoc """
  An access key for the storage account.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"keyName",
    :"value",
    :"permissions"
  ]

  @type t :: %__MODULE__{
    :"keyName" => String.t,
    :"value" => String.t,
    :"permissions" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Storage.Model.StorageAccountKey do
  def decode(value, _options) do
    value
  end
end

