# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.ApplicationGatewayUrlPathMapPropertiesFormat do
  @moduledoc """
  Properties of UrlPathMap of the application gateway.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"defaultBackendAddressPool",
    :"defaultBackendHttpSettings",
    :"defaultRedirectConfiguration",
    :"pathRules",
    :"provisioningState"
  ]

  @type t :: %__MODULE__{
    :"defaultBackendAddressPool" => SubResource,
    :"defaultBackendHttpSettings" => SubResource,
    :"defaultRedirectConfiguration" => SubResource,
    :"pathRules" => [ApplicationGatewayPathRule],
    :"provisioningState" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.ApplicationGatewayUrlPathMapPropertiesFormat do
  import Microsoft.Azure.Management.Network.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"defaultBackendAddressPool", :struct, Microsoft.Azure.Management.Network.Model.SubResource, options)
    |> deserialize(:"defaultBackendHttpSettings", :struct, Microsoft.Azure.Management.Network.Model.SubResource, options)
    |> deserialize(:"defaultRedirectConfiguration", :struct, Microsoft.Azure.Management.Network.Model.SubResource, options)
    |> deserialize(:"pathRules", :list, Microsoft.Azure.Management.Network.Model.ApplicationGatewayPathRule, options)
  end
end

