# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.ApplicationGatewayFirewallRule do
  @moduledoc """
  A web application firewall rule.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ruleId",
    :"description"
  ]

  @type t :: %__MODULE__{
    :"ruleId" => integer(),
    :"description" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.ApplicationGatewayFirewallRule do
  def decode(value, _options) do
    value
  end
end

