# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.ApplicationGatewayFirewallRuleGroup do
  @moduledoc """
  A web application firewall rule group.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ruleGroupName",
    :"description",
    :"rules"
  ]

  @type t :: %__MODULE__{
    :"ruleGroupName" => String.t,
    :"description" => String.t,
    :"rules" => [ApplicationGatewayFirewallRule]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.ApplicationGatewayFirewallRuleGroup do
  import Microsoft.Azure.Management.Network.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"rules", :list, Microsoft.Azure.Management.Network.Model.ApplicationGatewayFirewallRule, options)
  end
end

