# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.AzureReachabilityReportLatencyInfo do
  @moduledoc """
  Details on latency for a time series.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"timeStamp",
    :"score"
  ]

  @type t :: %__MODULE__{
    :"timeStamp" => DateTime.t,
    :"score" => integer()
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.AzureReachabilityReportLatencyInfo do
  def decode(value, _options) do
    value
  end
end

