# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.ConnectionMonitorSource do
  @moduledoc """
  Describes the source of connection monitor.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"resourceId",
    :"port"
  ]

  @type t :: %__MODULE__{
    :"resourceId" => String.t,
    :"port" => integer()
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.ConnectionMonitorSource do
  def decode(value, _options) do
    value
  end
end

