# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.ConnectivityInformation do
  @moduledoc """
  Information on the connectivity status.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"hops",
    :"connectionStatus",
    :"avgLatencyInMs",
    :"minLatencyInMs",
    :"maxLatencyInMs",
    :"probesSent",
    :"probesFailed"
  ]

  @type t :: %__MODULE__{
    :"hops" => [ConnectivityHop],
    :"connectionStatus" => String.t,
    :"avgLatencyInMs" => integer(),
    :"minLatencyInMs" => integer(),
    :"maxLatencyInMs" => integer(),
    :"probesSent" => integer(),
    :"probesFailed" => integer()
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.ConnectivityInformation do
  import Microsoft.Azure.Management.Network.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"hops", :list, Microsoft.Azure.Management.Network.Model.ConnectivityHop, options)
  end
end

