# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.EffectiveNetworkSecurityRule do
  @moduledoc """
  Effective network security rules.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"protocol",
    :"sourcePortRange",
    :"destinationPortRange",
    :"sourcePortRanges",
    :"destinationPortRanges",
    :"sourceAddressPrefix",
    :"destinationAddressPrefix",
    :"sourceAddressPrefixes",
    :"destinationAddressPrefixes",
    :"expandedSourceAddressPrefix",
    :"expandedDestinationAddressPrefix",
    :"access",
    :"priority",
    :"direction"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"protocol" => String.t,
    :"sourcePortRange" => String.t,
    :"destinationPortRange" => String.t,
    :"sourcePortRanges" => [String.t],
    :"destinationPortRanges" => [String.t],
    :"sourceAddressPrefix" => String.t,
    :"destinationAddressPrefix" => String.t,
    :"sourceAddressPrefixes" => [String.t],
    :"destinationAddressPrefixes" => [String.t],
    :"expandedSourceAddressPrefix" => [String.t],
    :"expandedDestinationAddressPrefix" => [String.t],
    :"access" => String.t,
    :"priority" => integer(),
    :"direction" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.EffectiveNetworkSecurityRule do
  def decode(value, _options) do
    value
  end
end

