# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.EffectiveRoute do
  @moduledoc """
  Effective Route
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"source",
    :"state",
    :"addressPrefix",
    :"nextHopIpAddress",
    :"nextHopType"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"source" => String.t,
    :"state" => String.t,
    :"addressPrefix" => [String.t],
    :"nextHopIpAddress" => [String.t],
    :"nextHopType" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.EffectiveRoute do
  def decode(value, _options) do
    value
  end
end

