# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.NetworkInterfaceDnsSettings do
  @moduledoc """
  DNS settings of a network interface.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"dnsServers",
    :"appliedDnsServers",
    :"internalDnsNameLabel",
    :"internalFqdn",
    :"internalDomainNameSuffix"
  ]

  @type t :: %__MODULE__{
    :"dnsServers" => [String.t],
    :"appliedDnsServers" => [String.t],
    :"internalDnsNameLabel" => String.t,
    :"internalFqdn" => String.t,
    :"internalDomainNameSuffix" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.NetworkInterfaceDnsSettings do
  def decode(value, _options) do
    value
  end
end

