# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.NetworkInterfacePropertiesFormat do
  @moduledoc """
  NetworkInterface properties. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"virtualMachine",
    :"networkSecurityGroup",
    :"ipConfigurations",
    :"dnsSettings",
    :"macAddress",
    :"primary",
    :"enableAcceleratedNetworking",
    :"enableIPForwarding",
    :"resourceGuid",
    :"provisioningState"
  ]

  @type t :: %__MODULE__{
    :"virtualMachine" => SubResource,
    :"networkSecurityGroup" => NetworkSecurityGroup,
    :"ipConfigurations" => [NetworkInterfaceIpConfiguration],
    :"dnsSettings" => NetworkInterfaceDnsSettings,
    :"macAddress" => String.t,
    :"primary" => boolean(),
    :"enableAcceleratedNetworking" => boolean(),
    :"enableIPForwarding" => boolean(),
    :"resourceGuid" => String.t,
    :"provisioningState" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.NetworkInterfacePropertiesFormat do
  import Microsoft.Azure.Management.Network.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"virtualMachine", :struct, Microsoft.Azure.Management.Network.Model.SubResource, options)
    |> deserialize(:"networkSecurityGroup", :struct, Microsoft.Azure.Management.Network.Model.NetworkSecurityGroup, options)
    |> deserialize(:"ipConfigurations", :list, Microsoft.Azure.Management.Network.Model.NetworkInterfaceIpConfiguration, options)
    |> deserialize(:"dnsSettings", :struct, Microsoft.Azure.Management.Network.Model.NetworkInterfaceDnsSettings, options)
  end
end

