# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.OperationPropertiesFormat do
  @moduledoc """
  Description of operation properties format.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"serviceSpecification"
  ]

  @type t :: %__MODULE__{
    :"serviceSpecification" => OperationPropertiesFormatServiceSpecification
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.OperationPropertiesFormat do
  import Microsoft.Azure.Management.Network.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"serviceSpecification", :struct, Microsoft.Azure.Management.Network.Model.OperationPropertiesFormatServiceSpecification, options)
  end
end

