# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.ProtocolConfiguration do
  @moduledoc """
  Configuration of the protocol.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"HTTPConfiguration"
  ]

  @type t :: %__MODULE__{
    :"HTTPConfiguration" => HttpConfiguration
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.ProtocolConfiguration do
  import Microsoft.Azure.Management.Network.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"HTTPConfiguration", :struct, Microsoft.Azure.Management.Network.Model.HttpConfiguration, options)
  end
end

