# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.TopologyAssociation do
  @moduledoc """
  Resources that have an association with the parent resource.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"resourceId",
    :"associationType"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"resourceId" => String.t,
    :"associationType" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.TopologyAssociation do
  def decode(value, _options) do
    value
  end
end

