# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.TroubleshootingDetails do
  @moduledoc """
  Information gained from troubleshooting of specified resource.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"reasonType",
    :"summary",
    :"detail",
    :"recommendedActions"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"reasonType" => String.t,
    :"summary" => String.t,
    :"detail" => String.t,
    :"recommendedActions" => [TroubleshootingRecommendedActions]
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.TroubleshootingDetails do
  import Microsoft.Azure.Management.Network.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"recommendedActions", :list, Microsoft.Azure.Management.Network.Model.TroubleshootingRecommendedActions, options)
  end
end

