# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Model.VirtualNetworkUsage do
  @moduledoc """
  Usage details for subnet.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"currentValue",
    :"id",
    :"limit",
    :"name",
    :"unit"
  ]

  @type t :: %__MODULE__{
    :"currentValue" => float(),
    :"id" => String.t,
    :"limit" => float(),
    :"name" => VirtualNetworkUsageName,
    :"unit" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Network.Model.VirtualNetworkUsage do
  import Microsoft.Azure.Management.Network.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"name", :struct, Microsoft.Azure.Management.Network.Model.VirtualNetworkUsageName, options)
  end
end

