# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Preview.Addons.Model.CanonicalSupportPlanProperties do
  @moduledoc """
  The properties of the Canonical support plan.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"provisioningState"
  ]

  @type t :: %__MODULE__{
    :"provisioningState" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Preview.Addons.Model.CanonicalSupportPlanProperties do
  def decode(value, _options) do
    value
  end
end

