# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Preview.Addons.Model.CanonicalSupportPlanInfoDefinition do
  @moduledoc """
  Definition object with the properties of a camonical plan
  """

  @derive [Poison.Encoder]
  defstruct [
    :"supportPlanType",
    :"enabled",
    :"oneTimeCharge"
  ]

  @type t :: %__MODULE__{
    :"supportPlanType" => String.t,
    :"enabled" => boolean(),
    :"oneTimeCharge" => String.t
  }
end

defimpl Poison.Decoder, for: Microsoft.Azure.Management.Preview.Addons.Model.CanonicalSupportPlanInfoDefinition do
  def decode(value, _options) do
    value
  end
end

