# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Subscription.Api.Subscriptions do
  @moduledoc """
  API calls for all endpoints tagged `Subscriptions`.
  """

  alias Microsoft.Azure.Management.Subscription.Connection
  import Microsoft.Azure.Management.Subscription.RequestBuilder


  @doc """
  Gets details about a specified subscription.

  ## Parameters

  - connection (Microsoft.Azure.Management.Subscription.Connection): Connection to server
  - subscription_id (String.t): The ID of the target subscription.
  - api_version (String.t): The API version to use for the operation.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Subscription.Model.Subscription{}} on success
  {:error, info} on failure
  """
  @spec subscriptions_get(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Subscription.Model.Subscription.t} | {:error, Tesla.Env.t}
  def subscriptions_get(connection, subscription_id, api_version, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/subscriptions/#{subscription_id}")
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Subscription.Model.Subscription{})
  end

  @doc """
  Gets all subscriptions for a tenant.

  ## Parameters

  - connection (Microsoft.Azure.Management.Subscription.Connection): Connection to server
  - api_version (String.t): The API version to use for the operation.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Subscription.Model.SubscriptionListResult{}} on success
  {:error, info} on failure
  """
  @spec subscriptions_list(Tesla.Env.client, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Subscription.Model.SubscriptionListResult.t} | {:error, Tesla.Env.t}
  def subscriptions_list(connection, api_version, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/subscriptions")
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Subscription.Model.SubscriptionListResult{})
  end

  @doc """
  Gets all available geo-locations.
  This operation provides all the locations that are available for resource providers; however, each resource provider may support a subset of this list.

  ## Parameters

  - connection (Microsoft.Azure.Management.Subscription.Connection): Connection to server
  - subscription_id (String.t): The ID of the target subscription.
  - api_version (String.t): The API version to use for the operation.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Subscription.Model.LocationListResult{}} on success
  {:error, info} on failure
  """
  @spec subscriptions_list_locations(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Subscription.Model.LocationListResult.t} | {:error, Tesla.Env.t}
  def subscriptions_list_locations(connection, subscription_id, api_version, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/subscriptions/#{subscription_id}/locations")
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Subscription.Model.LocationListResult{})
  end
end
