# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Microsoft.Azure.Management.Network.Api.ExpressRouteCrossConnectionArpTable do
  @moduledoc """
  API calls for all endpoints tagged `ExpressRouteCrossConnectionArpTable`.
  """

  alias Microsoft.Azure.Management.Network.Connection
  import Microsoft.Azure.Management.Network.RequestBuilder


  @doc """
  Gets the currently advertised ARP table associated with the express route cross connection in a resource group.

  ## Parameters

  - connection (Microsoft.Azure.Management.Network.Connection): Connection to server
  - resource_group_name (String.t): The name of the resource group.
  - cross_connection_name (String.t): The name of the ExpressRouteCrossConnection.
  - peering_name (String.t): The name of the peering.
  - device_path (String.t): The path of the device
  - api_version (String.t): Client API version.
  - subscription_id (String.t): The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Microsoft.Azure.Management.Network.Model.ExpressRouteCircuitsArpTableListResult{}} on success
  {:error, info} on failure
  """
  @spec express_route_cross_connections_list_arp_table(Tesla.Env.client, String.t, String.t, String.t, String.t, String.t, String.t, keyword()) :: {:ok, Microsoft.Azure.Management.Network.Model.ExpressRouteCircuitsArpTableListResult.t} | {:error, Tesla.Env.t}
  def express_route_cross_connections_list_arp_table(connection, resource_group_name, cross_connection_name, peering_name, device_path, api_version, subscription_id, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/subscriptions/#{subscription_id}/resourceGroups/#{resource_group_name}/providers/Microsoft.Network/expressRouteCrossConnections/#{cross_connection_name}/peerings/#{peering_name}/arpTables/#{device_path}")
    |> add_param(:query, :"api-version", api_version)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Microsoft.Azure.Management.Network.Model.ExpressRouteCircuitsArpTableListResult{})
  end
end
